spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/stac"
    username: stac
    password: stac
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG